version: '3.9'


services:
  delivery:
    build:
      context: .
      dockerfile: delivery_service/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - payment
    environment:
      - DATABASE_URL=sqlite:///./food_delivery.db
    container_name: delivery_service
    networks:
      - app-network

  payment:
    build:
      context: .
      dockerfile: payment_service/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=sqlite:///./payment.db
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 12345
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    container_name: keycloak
    networks:
      - app-network
    command: -v start-dev --import-realm

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - app-network
    command: -config.file=/etc/loki/local-config.yaml -target=all

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./docker-config.yaml:/etc/promtail/docker-config.yaml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - app-network
    command: -config.file=/etc/promtail/docker-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - GF_EXPLORE_ENABLED=true
    volumes:
      - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.max-block-duration=30m'
      - '--storage.tsdb.min-block-duration=30m'
      - '--web.enable-lifecycle'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'


  node:
    image: prom/node-exporter:latest
    container_name: node
    ports:
      - "9100:9100"
    networks:
      - app-network
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro


networks:
  app-network:
    driver: bridge

volumes:
  prometheus:
    name: prometheus
  grafana-storage:
    driver: local
